version: "2.4"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        
        # Just a blob to test recovery
        # command:
        #     - /bin/sh
        #     - -c
        #     - |
        #         nohup redis-server &
        #         sleep 5
        #         redis-cli SET fibonacci_current 5
        #         tail -f /dev/null

        restart: always

    app:
        build: .
        depends_on:
            - redis
        links:
            - redis

        init: true
        command: /app/fibonacci-backend

        cpu_count: 1
        cpus: 1

        mem_limit: 512m
        memswap_limit: 512m

        ports:
            - "8080:8080"
        
        
        environment:
            - SERVING_HOST_PORT=0.0.0.0:8080
            - REDIS_HOST_PORT=redis:6379
        
        healthcheck:
            test: curl -fail --retry 3 --max-time 5 --retry-delay 5 --retry-max-time 30 "http://0.0.0.0:8080/health" || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
            interval: 30s
            timeout: 2m
            retries: 1
            start_period: 10s

        restart: always
