version: "2.4"
services:
    web:
        build: .
        cpu_count: 1
        cpus: 1
        mem_limit: 512m
        memswap_limit: 512m
        ports:
            - "8080:8080"
        restart: always