version: "2.4"
services:
    app:
        build: .

        cpu_count: 1
        cpus: 1

        mem_limit: 512m
        memswap_limit: 512m

        ports:
            - "8080:8080"
        
        healthcheck:
            test: curl -fail --retry 3 --max-time 5 --retry-delay 5 --retry-max-time 30 "http://0.0.0.0:8080/health" || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
            interval: 30s
            timeout: 2m
            retries: 1
            start_period: 10s